version: '3.8'

services:
  blog:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 9229:9229
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:dev
    networks:
      - network
    depends_on:
      - redis
      - postgres
  postgres:
    image: postgres:13-alpine
    networks:
      - network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:${POSTGRES_PORT}
networks:
  network:
